config/routes.rb
Panoptic::Engine.routes.draw do
  root to: "processes#index"

  resources :queues, only: [:index]

  resources :jobs, only: :index do
    resource :retry, only: :create, module: :jobs
  end

  scope :jobs, module: :jobs do
    resources :scheduled, only: :index, as: :scheduled_jobs
    resources :failed, only: [:index, :show, :destroy], as: :failed_jobs
  end
end

app/models/panoptic/application_record.rb
module Panoptic
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/panoptic/failed_job.rb
# frozen_string_literal: true

module Panoptic
  class FailedJob < SolidQueue::Job
    # TODO: use the `failed` scope available in SolidQueue next release
    default_scope { includes(:failed_execution).where.not(failed_execution: { id: nil }) }

    def enqueued_at
      Time.parse(arguments["enqueued_at"])
    end

    def exception_class
      failed_execution.error["exception_class"]
    end

    def exception_message
      failed_execution.error["message"]
    end

    def stacktrace
      failed_execution.error["backtrace"]
    end
  end
end

app/models/panoptic/process.rb
# frozen_string_literal: true

module Panoptic
  class Process
    def self.supervisors
      SolidQueue::Process.where(supervisor_id: nil)
    end
  end
end

app/controllers/panoptic/application_controller.rb
module Panoptic
  class ApplicationController < ActionController::Base
    include Pagy::Backend
  end
end

app/controllers/panoptic/jobs/failed_controller.rb
# frozen_string_literal: true

module Panoptic
  class Jobs::FailedController < ApplicationController
    layout "panoptic/jobs", only: :index

    def index
      @pagy, @jobs = pagy(
        Panoptic::FailedJob.order(created_at: :asc)
      )
    end

    def show
      @job = Panoptic::FailedJob.find(params[:id])
    end

    def destroy
      @job = Panoptic::FailedJob.find(params[:id])
      if @job.destroy
        redirect_back fallback_location: failed_jobs_path,
                      notice: "Job was successfully deleted."
      else
        redirect_back fallback_location: failed_jobs_path,
                      alert: @job.errors.full_messages.to_sentence
      end
    end
  end
end

app/controllers/panoptic/jobs/retries_controller.rb
# frozen_string_literal: true

module Panoptic
  class Jobs::RetriesController < ApplicationController
    def create
      @job = SolidQueue::Job.find(params[:job_id])

      @job.retry
      redirect_to jobs_path, notice: "Successfully retried Job ##{@job.id}"
    end
  end
end

app/controllers/panoptic/jobs/scheduled_controller.rb
# frozen_string_literal: true

module Panoptic
  class Jobs::ScheduledController < ApplicationController
    layout "panoptic/jobs"

    def index
      # TODO: use the `scheduled` scope available in SolidQueue next release
      @pagy, @jobs = pagy(
        SolidQueue::Job.joins(:scheduled_execution).order(scheduled_at: :asc)
      )

      render "panoptic/jobs/index"
    end
  end
end

app/controllers/panoptic/jobs_controller.rb
# frozen_string_literal: true

module Panoptic
  class JobsController < ApplicationController
    def index
      @pagy, @jobs = pagy(SolidQueue::Job.order(created_at: :desc))
    end
  end
end

app/controllers/panoptic/processes_controller.rb
# frozen_string_literal: true

module Panoptic
  class ProcessesController < ApplicationController
    def index
      @hosts = Process.supervisors.includes(:forks)
    end
  end
end

app/controllers/panoptic/queues_controller.rb
# frozen_string_literal: true

module Panoptic
  class QueuesController < ApplicationController
    def index
      @queues = SolidQueue::Queue.all
    end
  end
end

app/helpers/panoptic/application_helper.rb
module Panoptic
  module ApplicationHelper
    include Pagy::Frontend
    include BreadcrumbsHelper
    include DateTimeHelper
  end
end

app/helpers/panoptic/breadcrumbs_helper.rb
# frozen_string_literal: true

module Panoptic
  module BreadcrumbsHelper
    def breadcrumb_items
      @breadcrumb_items ||= []
    end

    def breadcrumbs
      tag.nav(aria: { label: "breadcrumb" }) do
        tag.ol(class: "breadcrumb") do
          breadcrumb_items.map do |item|
            concat tag.li(item, class: "breadcrumb-item")
          end
        end
      end
    end
  end
end

app/helpers/panoptic/date_time_helper.rb
# frozen_string_literal: true

module Panoptic
  module DateTimeHelper
    def safe_time_tag(date_or_time, *args, &block)
      return "-" unless date_or_time

      time_tag(date_or_time, *args, &block)
    end
  end
end

app/views/layouts/panoptic/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panoptic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "panoptic/application" %>
    <%= javascript_include_tag "panoptic/application", defer: true %>
  </head>
  <body class="pb-4">

    <%= render "panoptic/shared/navbar" %>

    <main class="container mt-2">
      <%= render "panoptic/shared/flashes" %>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/layouts/panoptic/jobs.html.erb
<% content_for(:content) do %>
  <h1>Jobs</h1>

  <ul class="nav nav-underline">
    <li class="nav-item">
      <%= link_to "All", jobs_path, class: class_names("nav-link", "active": current_page?(jobs_path)) %>
    </li>
    <li class="nav-item">
      <%= link_to "Scheduled", scheduled_jobs_path, class: class_names("nav-link", "active": current_page?(scheduled_jobs_path)) %>
    </li>
    <li class="nav-item">
      <%= link_to "Failed", failed_jobs_path, class: class_names("nav-link", "active": current_page?(failed_jobs_path)) %>
    </li>
  </ul>

  <div class="d-flex justify-content-end">
    <%== pagy_info(@pagy)  %> 
  </div>
  
  <%= yield %>

  <div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
  </div>
<% end %>

<%= render template: "layouts/panoptic/application" %>

app/views/panoptic/jobs/_job.html.erb
<tr>
  <th scope="row"><%= job.id %></th>
  <td scope="col"><%= job.class_name %></td>
  <td scope="col"><%= job.queue_name %></td>
  <td scope="col"><%= safe_time_tag job.scheduled_at %></td>
  <td scope="col"><%= safe_time_tag job.finished_at %></td>
</tr>

app/views/panoptic/jobs/failed/_job.html.erb
<tr>
  <th scope="row"><%= job.id %></th>
  <td scope="col"><%= job.class_name %></td>
  <td scope="col"><%= job.queue_name %></td>
  <td scope="col" class="font-monospace"><%= job.exception_class %></td>
  <td scope="col"><%= safe_time_tag job.enqueued_at %></td>
  <td scope="col">
    <%= link_to "Details", failed_job_path(job), class: "btn btn-link" %>
    <%= button_to "Retry Job", job_retry_path(job),
          class: "btn btn-link",
          form_class: "d-inline" %>
    <%= button_to "Delete Job", failed_job_path(job),
          method: :delete,
          form: { data: { turbo_confirm: "Are you sure you want delete?" } },
          class: "btn btn-link text-danger",
          form_class: "d-inline" %>
  </td>
</tr>

app/views/panoptic/jobs/failed/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Class</th>
      <th scope="col">Queue</th>
      <th scope="col">Exception</th>
      <th scope="col">Enqueued</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "job", collection: @jobs %>  
  </tbody>
</table>

app/views/panoptic/jobs/failed/show.html.erb
<% breadcrumb_items.push link_to("Jobs", jobs_path) %>
<% breadcrumb_items.push link_to("Failed", failed_jobs_path) %>
<% breadcrumb_items.push @job.id %>
<%= breadcrumbs %>

<h1><%= @job.class_name %></h1>

<%= button_to "Retry Job", job_retry_path(@job), class: "btn btn-primary mb-3" %>

<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= @job.exception_class %></h4>
  <p class="font-monospace mb-0">
    <%= @job.exception_message %>
  </p>
</div>

<div class="card" >
  <div class="card-header">
    Stacktrace
  </div>
  <ul class="list-group list-group-flush font-monospace text-xs">
    <% @job.stacktrace.each do |trace| %>
      <li class="list-group-item"><%= trace %></li>
    <% end %>
  </ul>
</div>

app/views/panoptic/jobs/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Class</th>
      <th scope="col">Queue</th>
      <th scope="col">Scheduled</th>
      <th scope="col">Finished</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "panoptic/jobs/job", collection: @jobs %>  
  </tbody>
</table>

app/views/panoptic/processes/_process.html.erb
<li class="list-group-item">
  <h5><%= process.kind %></h5>
  
  <div>
    <span class="badge text-bg-primary">PID: <%= process.pid %></span>
    <span class="badge text-bg-secondary">Created: <%= time_ago_in_words process.created_at %></span> 
    <span class="badge text-bg-secondary">Last heartbeat: <%= time_ago_in_words process.last_heartbeat_at %></span> 
  </div>

  <div class="mt-2">
    <% process.metadata.each do |setting, value| %> 
      <div class="d-flex justify-content-between">
        <div><%= setting %></div>
        <div><%= value %></div>
      </div>
    <% end %>
  </div>
</li>

app/views/panoptic/processes/index.html.erb
<h1>Processes</h1>

<div class="d-grid gap-3">
  <% @hosts.each do |host| %>
    <div class="card">
      <div class="card-header">
        <b>Host:</b> <%= host.hostname %>
      </div>
      
      <ul class="list-group list-group-flush">
        <%= render partial: "process", collection: host.forks %>
      </ul>
    </div>
  <% end %>
</div>

app/views/panoptic/queues/_queue.html.erb
<li class="list-group-item">
  <b><%= queue.name %></b>
  <span class="badge text-bg-primary">Size: <%= queue.size %></span>
</li>

app/views/panoptic/queues/index.html.erb
<h1>Queues</h1>

<div class="card">
  <div class="card-header">
    Queue name
  </div>
  
  <ul class="list-group list-group-flush">
    <%= render partial: "queue", collection: @queues %>
  </ul>
</div>

app/views/panoptic/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
<% end %>

app/views/panoptic/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Panoptic", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Processes", root_path, class: class_names("nav-link", "active": current_page?(root_path)) %>
        </li>

        <li class="nav-item">
          <%= link_to "Queues", queues_path, class: class_names("nav-link", "active": current_page?(queues_path)) %>
        </li>

        <li class="nav-item">
          <%= link_to "Jobs", jobs_path, class: class_names("nav-link", "active": current_page?(jobs_path)) %>
        </li>
      </ul>
    </div>
  </div>
</nav>